name: env4LLM
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pip=25.0
  - numpy>=1.24.4
  - pandas>=2.0.3
  - matplotlib>=3.7.3
  - seaborn>=0.12.2
  - psutil>=5.9.6
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.23.2
    - pydantic==2.4.2
    - python-dotenv==1.0.0
    - python-multipart==0.0.6
    - starlette==0.27.0
    - elasticsearch==7.17.9
    - elasticsearch-dsl==7.4.1
    - langchain==0.0.335
    - langchain-core==0.1.1
    - dashscope==1.13.3
    - tabulate==0.9.0
    - jinja2==3.1.2
    - requests==2.31.0
    - pytest==7.4.3
    - pytest-asyncio==0.21.1
    - httpx==0.25.1
    - loguru==0.7.2


