name: env4LLM
channels:
  - defaults
dependencies:
  - ca-certificates=2025.2.25
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=25.0
  - python=3.9.21
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
    - aiohappyeyeballs==2.4.6
    - aiohttp==3.11.13
    - aiosignal==1.3.2
    - annotated-types==0.7.0
    - anyio==4.8.0
    - async-timeout==4.0.3
    - attrs==25.1.0
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - contourpy==1.3.0
    - cycler==0.12.1
    - exceptiongroup==1.2.2
    - filelock==3.17.0
    - fonttools==4.56.0
    - frozenlist==1.5.0
    - fsspec==2025.2.0
    - greenlet==3.1.1
    - h11==0.14.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - huggingface-hub==0.29.1
    - idna==3.10
    - importlib_resources==6.5.2
    - jinja2==3.1.5
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - kiwisolver==1.4.7
    - langchain==0.3.19
    - langchain-core==0.3.40
    - langchain-text-splitters==0.3.6
    - langsmith==0.3.11
    - markupsafe==3.0.2
    - matplotlib==3.9.4
    - mpmath==1.3.0
    - multidict==6.1.0
    - networkx==3.2.1
    - numpy==1.26.4
    - orjson==3.10.15
    - packaging==24.2
    - pandas==2.2.3
    - pillow==11.1.0
    - propcache==0.3.0
    - pydantic==2.10.6
    - pydantic_core==2.27.2
    - pyparsing==3.2.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.1
    - pyyaml==6.0.2
    - regex==2024.11.6
    - requests==2.32.3
    - requests-toolbelt==1.0.0
    - safetensors==0.5.3
    - six==1.17.0
    - sniffio==1.3.1
    - sqlalchemy==2.0.38
    - sympy==1.13.3
    - tenacity==9.0.0
    - tokenizers==0.21.0
    - torch==2.2.2
    - torchvision==0.17.2
    - tqdm==4.67.1
    - transformers==4.49.0
    - typing_extensions==4.12.2
    - urllib3==2.3.0
    - yarl==1.18.3
    - zipp==3.21.0
    - zstandard==0.23.0


