name: env4LLM
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pip=25.0
  - numpy>=1.26.4
  - pandas>=2.2.3
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - langchain==0.3.19
    - elasticsearch==8.17.1
    - python-dotenv==1.0.0
    - pydantic==2.10.6
    - python-multipart==0.0.6
    - jinja2==3.1.5
    - torch>=2.2.2
    - transformers>=4.49.0
    - sentence-transformers>=2.2.0
    - dashscope>=1.22.1
    - aiohttp>=3.11.13
    - requests>=2.32.3
    - tqdm>=4.67.1
    - matplotlib>=3.9.4
    - PyYAML>=6.0.2


